pipeline {
    agent any

    environment {
        CI = 'true'
    }

    stages {
        stage('SetupVM') {
            steps {
		sh 'cd /tmp/testing/vagrant'
		sh 'ls -la'
		sh 'vagrant/startup.sh'
                
            }
        }
	stage('Build'){
	   agent { label 'vagrant' }
	    steps {
		sh 'npm build'
	    }
	}
        stage('Test') {
		agent { label 'vagrant' }
            steps {
                sh 'npm test'
            }
        }
        stage('Deliver') {
		agent { label 'vagrant' }
            steps {
                sh 'npm build'
            }
        }
    }
}
